name: EcoAntiWither
main: jp.minecraftuser.ecoantiwither.EcoAntiWither
version: ${project.version}
depend: [EcoFramework]
commands:
  wither:
    description: reload config.yml
    usage: /wither reload
    permission: ecoantiwither
  wither reload:
    description: reload config.yml
    usage: /wither reload
    permission: ecoantiwither.reload
